CREATE DATABASE USER;
USE USER;
CREATE TABLE USER (
	id BIGINT PRIMARY KEY,
	NAME VARCHAR ( 20 ) NOT NULL,
	PASSWORD VARCHAR ( 20 ) NOT NULL,
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	) ENGINE = INNODB ;

	CREATE TABLE role (
	id BIGINT PRIMARY KEY,
	NAME VARCHAR ( 20 ) NOT NULL,
	user_id BIGINT NOT NULL,
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	) ENGINE = INNODB;
	CREATE TABLE resource (
	id BIGINT PRIMARY KEY,
	NAME VARCHAR ( 20 ),
	role_id BIGINT NOT NULL,
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = INNODB